brews:
  - install: |
      bin.install "exportloopref"
    tap:
      owner: kyoh86
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kyoh86/exportloopref
    description: An analyzer that finds exporting pointers for loop variables.
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    main: ./cmd/exportloopref
    hooks:
      post:
        - go get github.com/kyoh86/git-vertag
archives:
  - id: gzip
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
