name: Review
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v1
        with:
          level: info
          github_token: ${{ secrets.GITHUB_TOKEN }}
